name: Publish Docs (Nightly)

on:
  schedule:
    - cron: "15 2 * * *"  # 02:15 UTC nightly
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node deps and build CSS
        run: |
          npm ci || npm install
          npm run build:css

      - name: Export static docs
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python - <<'PY'
          from app.report.export_static import export_docs
          export_docs()
          PY

      - name: Commit docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git commit -m "chore(docs): nightly static export" || echo "No changes"

      - name: Push changes
        run: |
          git push


